authors:
  jkoblitz:
    name: Julia Koblitz
    description: Main Developer
    avatar: https://avatars.githubusercontent.com/u/22150395 
    url: https://github.com/JKoblitz
  juwitte:
    name: Julius F. Witte
    description: Data Engineer
    avatar: https://avatars.githubusercontent.com/u/19672422
    url: https://github.com/juwitte
  martinique:
    name: Martinique Frentrup
    description: Community Manager
    avatar: https://avatars.githubusercontent.com/u/54138776
    url: https://github.com/Martinique-F
